In [43]:
import pandas as pd
import numpy as np

In [82]:
df_product_events = pd.read_csv(r"C:\Users\ASUS\Documents\College folders\Placements\Projects\Product Analyst\Raw data\raw__product_events_202607171732.csv")

In [83]:
df_product_events

,event_id,event_name,user_id,account_id,deal_id,event_timestamp,ingested_at,event_date,platform,device_type,app_version,country_code,event_properties,is_test_event,source_system
0,ab8cf39c-549a-4dfa-9b25-51f9d8f71cfd,login,user_58,account_84,NaN,32:41.0,32:41.0,01/01/2026,web,mobile,1.0,DK,"{""feature_name"": ""automation"", ""source"": ""api""}",False,frontend
1,3f3dcab9-3955-45dd-b869-9f81fe209875,log_activity,user_58,account_84,deal_388,35:08.0,35:08.0,01/01/2026,web,desktop,1.0,UK,"{""feature_name"": ""deal"", ""source"": ""automation""}",False,frontend
2,ba7e8805-f24b-4791-86e9-e58c078e62cb,move_deal_stage,user_58,account_84,deal_465,36:03.0,36:03.0,01/01/2026,web,desktop,1.1,SE,"{""feature_name"": ""dashboard"", ""source"": ""autom...",False,frontend
3,33fd4ea1-89a9-4517-936c-99ae62626dec,login,user_58,account_84,NaN,37:56.0,37:56.0,NaN,mobile,desktop,2.1,DE,"{""feature_name"": ""dashboard"", ""source"": ""ui""}",False,frontend
4,885930dd-f793-4360-b2e2-69a7b885d526,log_activity,user_58,account_84,deal_765,40:49.0,40:49.0,01/01/2026,web,mobile,1.0,FR,"{""feature_name"": ""pipeline"", ""source"": ""ui""}",False,frontend
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61742,f2983930-d2ee-421b-a53f-ef48df968ede,view_dashboard,user_198,account_119,NaN,05:30.0,05:30.0,12/31/2029,mobile,mobile,2.1,NO,"{""feature_name"": ""pipeline"", ""source"": ""api""}",False,automation
61743,8c18442a-285f-4c0b-85ae-4c7f4202937f,create_deal,user_198,account_119,deal_236,06:29.0,06:29.0,12/31/2029,web,desktop,1.1,SE,"{""feature_name"": ""deal"", ""source"": ""ui"", ""pipe...",False,backend
61744,36c5419d-2d56-4357-8986-b315e535cb46,move_deal_stage,user_198,account_119,deal_746,08:10.0,08:10.0,12/31/2029,web,desktop,1.0,UK,"{""feature_name"": ""deal"", ""source"": ""ui"", ""pipe...",False,backend
61745,6b5a1103-eb43-460c-8ed4-aafcfff59909,enable_automation,user_198,account_119,NaN,09:32.0,09:32.0,NaN,mobile,mobile,1.0,UK,"{""feature_name"": ""pipeline"", ""source"": ""ui"", ""...",False,frontend
61746,dd12958f-d02c-4e39-9322-c53198144e7c,create_deal,user_198,account_119,deal_339,11:30.0,11:30.0,12/31/2029,mobile,mobile,1.1,NO,"{""feature_name"": ""dashboard"", ""source"": ""api"",...",False,automation

In [84]:
df_product_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61747 entries, 0 to 61746
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   event_id          61122 non-null  object
 1   event_name        61747 non-null  object
 2   user_id           60566 non-null  object
 3   account_id        61094 non-null  object
 4   deal_id           36995 non-null  object
 5   event_timestamp   61747 non-null  object
 6   ingested_at       61747 non-null  object
 7   event_date        56806 non-null  object
 8   platform          61747 non-null  object
 9   device_type       61747 non-null  object
 10  app_version       61747 non-null  float64
 11  country_code      61747 non-null  object
 12  event_properties  61747 non-null  object
 13  is_test_event     61747 non-null  bool
 14  source_system     61747 non-null  object
dtypes: bool(1), float64(1), object(13)
memory usage: 6.7+ MB

In [85]:
df_product_events.isnull().sum()

event_id              625
event_name              0
user_id              1181
account_id            653
deal_id             24752
event_timestamp         0
ingested_at             0
event_date           4941
platform                0
device_type             0
app_version             0
country_code            0
event_properties        0
is_test_event           0
source_system           0
dtype: int64

In [86]:
date_columns = ['event_date']  # to convert date columns from object to date
df_product_events[date_columns] = df_product_events[date_columns].apply(pd.to_datetime)

In [87]:
df_product_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61747 entries, 0 to 61746
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   event_id          61122 non-null  object
 1   event_name        61747 non-null  object
 2   user_id           60566 non-null  object
 3   account_id        61094 non-null  object
 4   deal_id           36995 non-null  object
 5   event_timestamp   61747 non-null  object
 6   ingested_at       61747 non-null  object
 7   event_date        56806 non-null  datetime64[ns]
 8   platform          61747 non-null  object
 9   device_type       61747 non-null  object
 10  app_version       61747 non-null  float64
 11  country_code      61747 non-null  object
 12  event_properties  61747 non-null  object
 13  is_test_event     61747 non-null  bool
 14  source_system     61747 non-null  object
dtypes: bool(1), datetime64[ns](1), float64(1), object(12)
memory usage: 6.7+ MB

In [88]:
df_product_events['event_month'] = df['event_date'].dt.month_name()

In [89]:
df_product_events['event_name'].unique()

array(['login', 'log_activity', 'move_deal_stage', 'create_deal',
       'view_dashboard', 'invite_user', 'enable_automation', 'user_login',
       'ViewDashboard', 'Login'], dtype=object)

In [90]:
df_product_events['has_deal_category'] = np.nan
df_product_events['has_deal_category'] = df_product_events['has_deal_category'].astype('object')

In [91]:
import mysql.connector as connection
from mysql.connector import Error

mydb = connection.connect(host='localhost',user='root',password='BobySQL2026',database='product_analysis', use_pure=True)

In [92]:
cursor = mydb.cursor()

In [93]:
from sqlalchemy import create_engine
db_credentials = "mysql+pymysql://root:BobySQL2026@localhost:3306/product_analysis"
engine = create_engine(db_credentials)

silver_product_analysis = df
silver_product_analysis.to_sql(
    name = "silver_product_event",
    con = engine,
    if_exists = 'replace',
    index = False
)

61747

In [50]:
query = " SELECT * FROM silver_product_event"
cursor.execute(query)

In [52]:
tables = cursor.fetchall()

In [94]:
df_product_events

,event_id,event_name,user_id,account_id,deal_id,event_timestamp,ingested_at,event_date,platform,device_type,app_version,country_code,event_properties,is_test_event,source_system,event_month,has_deal_category
0,ab8cf39c-549a-4dfa-9b25-51f9d8f71cfd,login,user_58,account_84,NaN,32:41.0,32:41.0,2026-01-01,web,mobile,1.0,DK,"{""feature_name"": ""automation"", ""source"": ""api""}",False,frontend,January,NaN
1,3f3dcab9-3955-45dd-b869-9f81fe209875,log_activity,user_58,account_84,deal_388,35:08.0,35:08.0,2026-01-01,web,desktop,1.0,UK,"{""feature_name"": ""deal"", ""source"": ""automation""}",False,frontend,January,NaN
2,ba7e8805-f24b-4791-86e9-e58c078e62cb,move_deal_stage,user_58,account_84,deal_465,36:03.0,36:03.0,2026-01-01,web,desktop,1.1,SE,"{""feature_name"": ""dashboard"", ""source"": ""autom...",False,frontend,January,NaN
3,33fd4ea1-89a9-4517-936c-99ae62626dec,login,user_58,account_84,NaN,37:56.0,37:56.0,NaT,mobile,desktop,2.1,DE,"{""feature_name"": ""dashboard"", ""source"": ""ui""}",False,frontend,NaN,NaN
4,885930dd-f793-4360-b2e2-69a7b885d526,log_activity,user_58,account_84,deal_765,40:49.0,40:49.0,2026-01-01,web,mobile,1.0,FR,"{""feature_name"": ""pipeline"", ""source"": ""ui""}",False,frontend,January,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61742,f2983930-d2ee-421b-a53f-ef48df968ede,view_dashboard,user_198,account_119,NaN,05:30.0,05:30.0,2029-12-31,mobile,mobile,2.1,NO,"{""feature_name"": ""pipeline"", ""source"": ""api""}",False,automation,December,NaN
61743,8c18442a-285f-4c0b-85ae-4c7f4202937f,create_deal,user_198,account_119,deal_236,06:29.0,06:29.0,2029-12-31,web,desktop,1.1,SE,"{""feature_name"": ""deal"", ""source"": ""ui"", ""pipe...",False,backend,December,NaN
61744,36c5419d-2d56-4357-8986-b315e535cb46,move_deal_stage,user_198,account_119,deal_746,08:10.0,08:10.0,2029-12-31,web,desktop,1.0,UK,"{""feature_name"": ""deal"", ""source"": ""ui"", ""pipe...",False,backend,December,NaN
61745,6b5a1103-eb43-460c-8ed4-aafcfff59909,enable_automation,user_198,account_119,NaN,09:32.0,09:32.0,NaT,mobile,mobile,1.0,UK,"{""feature_name"": ""pipeline"", ""source"": ""ui"", ""...",False,frontend,NaN,NaN
61746,dd12958f-d02c-4e39-9322-c53198144e7c,create_deal,user_198,account_119,deal_339,11:30.0,11:30.0,2029-12-31,mobile,mobile,1.1,NO,"{""feature_name"": ""dashboard"", ""source"": ""api"",...",False,automation,December,NaN